project_id = "mdwpmbmesoxxbamvdwqa"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322

[studio]
enabled = true
port = 54323

[inbucket]
enabled = true
port = 54324
smtp_port = 54325
pop3_port = 54326

[functions.ai-carbon-recommendations]
verify_jwt = false
[functions.ai-receipt-parser]
verify_jwt = false
[functions.get-dashboard-data]
verify_jwt = false
[functions.get-enhanced-dashboard-data]
verify_jwt = false
[functions.process-receipt]
verify_jwt = false
[functions.scan-item]
verify_jwt = false
[functions.scan-barcode]
verify_jwt = false