// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mdwpmbmesoxxbamvdwqa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1kd3BtYm1lc294eGJhbXZkd3FhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIzMjgxMDMsImV4cCI6MjA2NzkwNDEwM30.VoaIXbvZT1nbL2BUxHWQtCgtHsCINDkGFGAojTUuQEQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});